### ISSUE TITLE
Auto play audio as well?

### ISSUE THREAD

**Issue by jorgb** [Wapply/obsidian-autoplay-and-loop#1]
Hi, just came across your plugin and I have been looking for something like this. Is it possible to also include .wav and .mp3 to auto play?

My use case is that I have a large sample library with riffs and melodics, and I want to randomize playing audio back based on tag(s). I use obsidian notes for aggregation of these sample references, and random plugin to randomize search results. It would be great if the sample starts auto playing as well.

Thanks!

**Comment by Wapply** [comment]
> Hi, just came across your plugin and I have been looking for something like this. Is it possible to also include .wav and .mp3 to auto play?
> 
> My use case is that I have a large sample library with riffs and melodics, and I want to randomize playing audio back based on tag(s). I use obsidian notes for aggregation of these sample references, and random plugin to randomize search results. It would be great if the sample starts auto playing as well.
> 
> Thanks!

Thanks for the suggestion and sorry for the delay. We have implemented functionality to include automatic playback of "audio" files in the plugin. Additionally, we added an options menu in Obsidian so you can turn audio and video autoplay on or off based on your preferences. ❤️

**Comment by jorgb** [comment]
Thanks for implementing this! I will give it a try!
